naam: Bug Rapport
omschrijving: Meld een bug
titel: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: wat-gebeurde-er
    attributes:
      label: Wat gebeurde er?
      description: Vertel ons ook, wat had je verwacht dat er zou gebeuren?
      placeholder: Vertel ons wat je ziet!
      value: "Er trad een bug op!"
    validations:
      required: true
  - type: textarea
    id: stappen-om-te-reproduceren
    attributes:
      label: Stappen om de bug te reproduceren
      description: Geef gedetailleerde stappen om het probleem te reproduceren.
      placeholder: Beschrijf de exacte stappen die je hebt genomen die tot het probleem hebben geleid.
      value: "1. Stap 1\n2. Stap 2\n3. Stap 3"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevante loguitvoer
      description: Kopieer en plak eventuele relevante loguitvoer. Dit wordt automatisch opgemaakt als code, dus geen behoefte aan backticks.
      render: shell
