name: Publish Leertaken

on:
  release:
    types: [prereleased, released]

  workflow_dispatch:
    inputs:
      tag:
        description: 'New version number'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME:  tiesgreve/leertaken

jobs:
  build-and-push-leertaken:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push leertaken image
        run: docker build --push --tag ghcr.io/${{ env.IMAGE_NAME }}:${{ inputs.tag }} -f quartz/.

      - name: Cleanup docker images
        run: docker image prune -f -a
